### ISSUE TITLE
typo in warning message at AutoTexturing.cs

### ISSUE THREAD

**Issue by thinpedelica** [Project-PLATEAU/PLATEAU-SDK-Toolkits-for-Unity#3]
# 内容
ワーニングメッセージに誤りがある。

「MeshRendererやMeshFilterが見つからなかったため最小値物単位のLOD２として扱います。」

×：最小値物単位
〇: 最小地物単位

# 発生方法
Hieralchy上でPlateauの建物のGameObjectを選択した状態で
自動テクスチャ生成 -> 自動生成 を選択。

# バージョン
v0.2.2

<img width="1021" alt="typo_in_warning_msg" src="https://github.com/Project-PLATEAU/PLATEAU-SDK-Toolkits-for-Unity/assets/24548199/705deaff-abde-42cd-ba17-21d727f76e93">

**Comment by unity-takeuchi** [comment]
Toolkitをご利用いただきありがとうございます。
新しいバージョンでメッセージを修正いたしました。
