### ISSUE TITLE
READMEとLICENSEに矛盾がある

### ISSUE THREAD

**Issue by earth2001y** [Project-PLATEAU/PLATEAU-SDK-Toolkits-for-Unity#5]
READMEには、

> * ソースコードおよび関連ドキュメントの著作権は国土交通省に帰属します

と書いてありますが、LICENSE には

> `Copyright (c) 2023 unity-shimizu` 

とあります。

**Comment by unity-takeuchi** [comment]
Toolkitをご利用いただきありがとうございます。
ご指摘の通り、LICENSEの表記に誤りがあったため修正いたしました。
